name: Upload /dist/* to Server

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TW_DEPLY_KEY }}" > ${{ secrets.SSH_KEY_PATH }}
        chmod 600 ${{ secrets.SSH_KEY_PATH }}
        ssh-keyscan ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TW_DEPLY_KEY }}
    - name: Upload files to server
      run: |
        scp -i ${{ secrets.SSH_KEY_PATH }} -r ./dist/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }} ${{ secrets.REMOTE_DIR }}
