name: Upload /dist/* to Server

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TW_DEPLY_KEY }}" > ~/.ssh/id_ed255_tw_github
        chmod 600 ~/.ssh/id_ed255_tw_github
        ssh-keyscan 85.193.83.189 >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TW_DEPLY_KEY }}
    - name: Upload files to server
      run: |
        scp -r ./dist/* root@85.193.83.189:/var/www/clients/client0/web17/web
