name: Upload /dist/* to Server

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
        SSH_KEY_PATH: ${{ vars.SSH_KEY_PATH }}
        REMOTE_SERVER: ${{ vars.REMOTE_SERVER }}
        
    steps:
    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TW_DEPLY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed255_tw_github
        chmod 600 ~/.ssh/id_ed255_tw_github
        ssh-keyscan 85.193.83.189 >> ~/.ssh/known_hosts
      
    - name: Upload files to server
      env:
        REMOTE_USER: ${{ vars.REMOTE_USER }}
        REMOTE_DIR: ${{ vars.REMOTE_DIR }}
      run: |
        scp -i ~/.ssh/id_ed255_tw_github -r ./dist/* root@85.193.83.189 /var/www/clients/client0/web17/web
